### PR TITLE
Alloy editor placeholder returns blank string rather than CKEditor default

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @ambrinchaudhary,

This is an update for [AUI-3088](https://issues.liferay.com/browse/AUI-3088).

I know the Alloy Editor project usually uses GitHub issues to fix bugs; would you like me to open an issue for this so it can be tracked on GitHub or will the JIRA ticket be enough?

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/antoniopol06/alloy-editor/pull/5. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
hey @dustinryerson, I am re-sending this PR to @antoniopol06, he would review it. Thanks!

**Comment by dustinryerson** [comment]
Thank you very much, @ambrinchaudhary!

**Pull request closed without merging**
